### ISSUE TITLE
Issues reusing 0.2.x / 0.1.x testnet wallets with newer version of bitcore-wallet-client

### ISSUE THREAD

**Issue by srw** [bitpay/bitcore-wallet-client#148]
We are using some (bitcore-wallet-client 0.2.x based) testnet wallets but when we try to use them with a newer version (0.6.0) we have the following exception. I am not sure what does it mean, could you give me any insight? Thanks. BTW we don't have issues with newly created testnet wallets.

Error: Illegal Argument.
    at Object.validatorFunctions.checkArgument (........../node_modules/bitcore-wallet-client/node_modules/preconditions/src/validatorFunctions.js:191:15)
    at Function.WalletUtils.deriveAddress (........../node_modules/bitcore-wallet-client/node_modules/bitcore-wallet-utils/lib/walletutils.js:84:5)
    at Function.Verifier.checkAddress (........../node_modules/bitcore-wallet-client/lib/verifier.js:28:27)
    at Function.Verifier.checkTxProposalBody (........../node_modules/bitcore-wallet-client/lib/verifier.js:129:17)
    at Function.Verifier.checkTxProposal (........../node_modules/bitcore-wallet-client/lib/verifier.js:148:13)
    at ........../node_modules/bitcore-wallet-client/lib/api.js:1180:34
    at API.getPayPro (........../node_modules/bitcore-wallet-client/lib/api.js:1210:12)
    at async.every.result.txps (........../node_modules/bitcore-wallet-client/lib/api.js:1178:14)
    at ........../node_modules/async/lib/async.js:376:13
    at ........../node_modules/async/lib/async.js:122:13

**Comment by isocolsky** [comment]
Hi, what version of BWS are you running?

**Comment by srw** [comment]
We are using BitPay's BWS.

**Comment by isocolsky** [comment]
Just so you know, this error occurs when the change address of a tx proposal cannot be verified. Was there an existing pending tx proposal when you updated your version of BWC?

**Comment by srw** [comment]
That is possible. What is the best way to check this in our code when we receive a new proposal? calling the Verifier.checkaddress ourselves? Thanks!

**Comment by isocolsky** [comment]
To go deeper into the issue, this line:
https://github.com/bitpay/bitcore-wallet-client/blob/master/lib/verifier.js#L28
is passing the address type as a first argument. This could be either `P2SH` or `P2PKH` for shared or 1-of-1 wallets respectively. In recent versions of BWS, the server will assign they `type` attribute to every address it creates so this code will work without issues.
I'm suspecting the wallet with a problem had a pending tx proposal created with an older version of BWS (one which did not assign the `type` attribute). And since `credentials.addressType` did not exist at the moment of wallet creation, the passed argument is `undefined`.
If this is indeed what is happening, adding a default value to `credentials.addressType` should fix the issue.
If you are using BWC, please continue to do so. I'll send you an updated version.
Thanks.

**Comment by isocolsky** [comment]
bitcore-wallet-client@0.6.3 is already on npm. Could you please try accessing your wallet with this version?

**Comment by srw** [comment]
Thank you very much, it works now.

**Comment by isocolsky** [comment]
Great! Thanks for reporting and testing!
