### ISSUE TITLE
Cannot find module '../node_modules/grunt/lib/grunt'

### ISSUE THREAD

**Issue by troggy** [bitpay/bitcore-wallet-client#186]
Installing and building like following:
````
git clone https://github.com/bitpay/bitcore-wallet-client
cd bitcore-wallet-client
npm i
make clean all
````

gives an error. Output:

````
rm bitcore-wallet-client.js
rm bitcore-wallet-client.min.js
node_modules/.bin/browserify index.js > bitcore-wallet-client.js
node_modules/.bin/uglify  -s bitcore-wallet-client.js  -o bitcore-wallet-client.min.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/grunt/lib/grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/troggy/tmp/bitcore-wallet-client/node_modules/uglify/lib/uglify.js:6:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
make: *** [bitcore-wallet-client.min.js] Error 8
````

Tried on different machines, same result

**Comment by troggy** [comment]
This works:
````
npm install -g uglify
uglify  -s bitcore-wallet-client.js  -o bitcore-wallet-client.min.js
````
