### ISSUE TITLE
createAddress recursion problem

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore-wallet-client#292]
Hello,
I try to generate many addresses for many wallets to make mass txProposal. As I found I can't generate them in simple cycle, `GET /insight-api/addr/` begin to return 500 code very soon.
So I try to generate addresses recursively like:

```
WalletsProcessor.prototype.getAddress = function(res, list, i, outputs, wfile, wpwd) 
{ 
    console.log("getAddress");
  var self = this;

	// 1. Open wallet & request address
	var client = new Client({
  		baseUrl: BWS_INSTANCE_URL,
    	verbose: false,
    });
    
    var walletName = list[i].wallet;
    
  try
  {
	// Open wallet's file
    client.import(fs.readFileSync(walletPath+walletName).toString());
	// Get address
	client.createAddress({}, function(err,addr)
    {
        console.log("createAddress callback");
    	if (err) 
        {
        	console.log('error: ', err);
            return;
        }
		var address = addr.address;
        console.log(address);
        var output = {amount:helper.BTCtoSatoshis(list[i].amnt), toAddress:address, message:i.toString(10)};
        outputs.push(output);
		client = null;	
        i++;
        if(i<10)
        {
            self.getAddress(res, list, i, outputs, wfile, wpwd);            
        }
	});
  }
    catch(e)
    {
        self.showMessage(res, 'Wallet access error', e);
    }
}

```
When I executed 
```
    var i=0;    
    self.getAddress(res, list, i, outputs, wname, wpwd);

```
I expect to see 10 addresses generation.
But I see following:
```
getAddress
[2016-06-22T15:01:06.805Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mskVqs5idhsjJGyXRkWfbaAVc14radtz8x" 200 257 8.945 "bws-1.9.0" 
[2016-06-22T15:01:06.817Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mgQZpTXQmnypEUiPbiYuRTxhTYjqxDkHX6" 200 257 3.754 "bws-1.9.0" 
[2016-06-22T15:01:06.824Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mzB3PNDX47YE7FdhUn5GQAYSXdWRqffDUU" 200 257 3.253 "bws-1.9.0" 
[2016-06-22T15:01:06.830Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mxDM71gkCbTmXDFAcTAsZKJH19TDxdrq5Q" 200 257 2.979 "bws-1.9.0" 
[2016-06-22T15:01:06.838Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/n3F6Sd3qS8L1WDb1sYhKSa82xsgTuZ9Bh8" 200 257 3.982 "bws-1.9.0" 
[2016-06-22T15:01:06.845Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/n3D4LWZX9gGXZ1pSdWCZWjffXzX22PfSxA" 200 257 2.463 "bws-1.9.0" 
[2016-06-22T15:01:06.858Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/moMNybQuP45YQspc8r6reQ5ozLD7cqvtVt" 200 257 3.054 "bws-1.9.0" 
[2016-06-22T15:01:06.865Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mvNhi4fVpu3mUHDANRv6GDXSQTakaHMKdn" 200 257 3.212 "bws-1.9.0" 
[2016-06-22T15:01:06.870Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mq5UiiMYLECfjAiRpjuXh7r1BCNs598e6a" 200 257 2.273 "bws-1.9.0" 
[2016-06-22T15:01:06.877Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mhUd6vCXL9ayvrDJqR4ewuEQag26VfBbpH" 200 257 2.693 "bws-1.9.0" 
[2016-06-22T15:01:06.882Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mh8G2koVSCrCz9RtgEi3aMdharkkWwLrze" 200 257 2.222 "bws-1.9.0" 
[2016-06-22T15:01:06.889Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/msfWtyrkCBadWHT1QDdFgQaFfY1B4XFLiT" 200 257 3.303 "bws-1.9.0" 
[2016-06-22T15:01:06.896Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mhCu2oCiEUtK8Bjn965g3UX6XrCuqwVU5o" 200 257 3.698 "bws-1.9.0" 
[2016-06-22T15:01:06.902Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mo2rCEsyeZ1kLvUrHQARn4xMrm8s8KZoD7" 200 257 2.991 "bws-1.9.0" 
[2016-06-22T15:01:06.908Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mwMpQzXFiVpqSNsXrFLRNU6rUZwSpU9NxB" 200 257 2.700 "bws-1.9.0" 
[2016-06-22T15:01:06.914Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mjQeyBb7qVgovaka6o19GAJVgTQrZKeEsu" 200 257 2.691 "bws-1.9.0" 
[2016-06-22T15:01:06.920Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/miCztTgweARAqTjJA2SaGgZhez7KTHReyh" 200 257 2.941 "bws-1.9.0" 
[2016-06-22T15:01:06.927Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mztFFFypSDQThL3HVaiZNhh2jGCtjhAg98" 200 257 2.621 "bws-1.9.0" 
[2016-06-22T15:01:06.933Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/mfvVe2EfdLoxbR8QwqF85eJUFztWMw3ABD" 200 257 3.294 "bws-1.9.0" 
[2016-06-22T15:01:06.939Z] info: ::ffff:127.0.0.1 "GET /insight-api/addr/muQJu1HAF8vdAemMZT3a3AyafrLXExUZdj" 200 257 3.567 "bws-1.9.0" 
info Client Err: 400 /v3/addresses/ <ClientError:MAIN_ADDRESS_GAP_REACHED Maximum number of consecutive addresses without activity reached> 
 ::ffff:127.0.0.1 2016-06-22T15:01:06.943Z "POST /bws/api/v3/addresses/" 400 112 177.758 "-" 7c56481a-4b84-4976-a547-9833a2e9def3 6c01c83aa08da31f99a34e251d979536602770d44286d7a65238b1bc9557b67c
[error] Error: MAIN_ADDRESS_GAP_REACHED
[2016-06-22T15:01:06.948Z] error: uncaught exception: [TypeError: Cannot read property 'type' of undefined]
[2016-06-22T15:01:06.948Z] error: TypeError: Cannot read property 'type' of undefined
    at Function.Verifier.checkAddress (/Users/iev/Documents/bitcore-wallet-service/node_modules/mynode/node_modules/bitcore-wallet-client/lib/verifier.js:28:42)
    at /Users/iev/Documents/bitcore-wallet-service/node_modules/mynode/node_modules/bitcore-wallet-client/lib/api.js:1811:19
    at Request._callback (/Users/iev/Documents/bitcore-wallet-service/node_modules/mynode/node_modules/bitcore-wallet-client/lib/api.js:813:14)
    at Request.self.callback (/Users/iev/Documents/bitcore-wallet-service/node_modules/mynode/node_modules/bitcore-wallet-client/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/iev/Documents/bitcore-wallet-service/node_modules/mynode/node_modules/bitcore-wallet-client/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/iev/Documents/bitcore-wallet-service/node_modules/mynode/node_modules/bitcore-wallet-client/node_modules/request/request.js:988:12)
[2016-06-22T15:01:06.949Z] info: Beginning shutdown
[2016-06-22T15:01:06.949Z] info: Stopping user
[2016-06-22T15:01:06.950Z] info: Stopping bitcore-wallet-service
[2016-06-22T15:01:06.950Z] info: Stopping insight-api
[2016-06-22T15:01:06.950Z] info: Stopping web
[2016-06-22T15:01:06.950Z] info: Stopping admin
[2016-06-22T15:01:06.950Z] info: Stopping bitcoind
[2016-06-22T15:01:11.758Z] warn: ZMQ disconnect: tcp://127.0.0.1:28332
[2016-06-22T15:01:11.759Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332

```
Looks like the only part of callback executed is getAddress func.
```
list = 
[ { wallet: 'testwallet1', amnt: 0.0101 },
  { wallet: 'testwallet2', amnt: 0.0102 },
  { wallet: 'testwallet3', amnt: 0.0103 },
  { wallet: 'testwallet4', amnt: 0.0104 },
  { wallet: 'testwallet5', amnt: 0.0105 },
  { wallet: 'testwallet6', amnt: 0.0106 },
  { wallet: 'testwallet7', amnt: 0.0107 },...
```
etc. 200 entries

**Comment by dabura667** [comment]
[error] Error: MAIN_ADDRESS_GAP_REACHED

GAP REACHED

so if you look at createAddress, the options say:

```javascript
 * @param {Boolean} opts.ignoreMaxGap[=false]
```
So make it true. Now you can generate unlimited.
```javascript
    // Get address
    client.createAddress({ignoreMaxGap: true}, function(err,addr)
```

**Comment by dabura667** [comment]
By the way, createAddress will always generate a brand new address, but if you want to view all your addresses up until now (maybe utilize unused old addresses for something)

Use

client.getMainAddresses Instead

**Comment by igorvlassov** [comment]
@dabura667 thanks a lot for your help.
Seems was my bag, sorry.
